@echo off
ECHO Activating the conda environment...
call conda activate
ECHO Launching the program...
ECHO Launching the browser...
"C:\Program Files\Mozilla Firefox\firefox" http://127.0.0.1:8052/ -ftimeout=10 
python pid_GUI.py
call conda deactivate