@echo off
ECHO Activating the conda environment...
call conda.bat activate
ECHO Launching the program...
ECHO Launching the browser...
"C:\Program Files\Mozilla Firefox\firefox" http://127.0.0.1:8054/ -ftimeout=10 
python sweeper_gui.py -p 127.0.0.1:8054
call conda.bat deactivate
